apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.webhook.certificate.name }} 
  namespace: {{ .Values.global.namespace }}
spec:
  isCA: true
  commonName: {{ .Values.webhook.serviceName }}.{{ .Values.global.namespace }}.svc
  dnsNames:
  - {{ .Values.webhook.serviceName }}.{{ .Values.global.namespace }}.svc
  - {{ .Values.webhook.serviceName }}.{{ .Values.global.namespace }}.svc.cluster.local
  secretName: {{ .Values.webhook.certificate.secretName }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.webhook.certificate.issuerName }}
    kind: Issuer
    group: cert-manager.io
