apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{.Values.webhook.mutatingWebhookName}}
  annotations:
    cert-manager.io/inject-ca-from: {{.Values.global.namespace}}/{{.Values.webhook.certificate.name}}

webhooks:
- name: webhook.vlanman.dialo.ai
  timeoutSeconds: 30
  failurePolicy: Fail
  admissionReviewVersions: ["v1"]
  sideEffects: NoneOnDryRun
  clientConfig:
    service:
      namespace: {{.Values.global.namespace}}
      name: {{.Values.webhook.serviceName}}
      path: /mutating
      port:  443
  # this is here to prevent a deadlock
  # since the webhook server is itself
  # a pod, without it it would try to
  # call itself on creation.
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - {{.Values.global.namespace}}
          
  objectSelector: {}
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
