apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{.Values.webhook.validatingWebhookName}}
  annotations:
    cert-manager.io/inject-ca-from: {{.Values.global.namespace}}/{{.Values.webhook.certificate.name}}
webhooks:
- name: webhook.vlanman.dialo.ai
  # failurePolicy: Fail
  admissionReviewVersions: ["v1"]
  sideEffects: None
  clientConfig:
    service:
      namespace: {{.Values.global.namespace}}
      name: {{.Values.webhook.serviceName}}
      path: /validating
      port:  443
  # this is here to prevent a deadlock
  # since the webhook server is itself
  # a pod, without it it would try to
  # call itself on creation.
  objectSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: NotIn
        values:
          - {{ include "vlanman.name" .}}
      - key: control-plane
        operator: NotIn
        values:
          - controller-manager
  rules:
  - operations: ["CREATE", "DELETE", "UPDATE"]
    apiGroups: ["vlanman.dialo.ai"]
    apiVersions: ["v1"]
    resources: ["vlannetworks"]
