apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vlannetworks.vlanman.dialo.ai
spec:
  group: vlanman.dialo.ai
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                gatewayIp:
                  type: string
                  format: ipv4
                excludedNodes:
                  type: array
                  items:
                    type: string
                localSubnet:
                  type: string
                remoteSubnet:
                  type: string
                vlanId:
                  type: integer
              required:
                - gatewayIp
                - localSubnet
                - remoteSubnet
                - vlanId
            status:
              type: object
              properties:
                active:
                  type: boolean
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: VLAN ID
          type: integer
          jsonPath: .spec.vlanId
        - name: Gateway IP
          type: string
          jsonPath: .spec.gatewayIp
        - name: Active
          type: boolean
          jsonPath: .status.active
  scope: Cluster
  names:
    plural: vlannetworks
    singular: vlannetwork
    kind: VlanNetwork
    shortNames:
      - vlan
