apiVersion: v1
kind: Service
metadata:
  name: {{.Values.webhook.serviceName}}
  namespace: {{.Values.global.namespace}}
spec:
  ports:
  - port: 443
    name: "webhook"
    protocol: TCP
    targetPort: 8443

  selector:
    app.kubernetes.io/name: {{include "vlanman.name" .}}
    control-plane: controller-manager
