apiVersion: v1
kind: Pod
metadata:
  name: netwithgw1-pod-1
  annotations:
    vlanman.dialo.ai/network: netwithgw1
    vlanman.dialo.ai/pool: primary
  labels:
    vlanman.dialo.ai/worker: netwithgw1
spec:
  initContainers:
    - env:
        - name: VLAN_NETWORK
          value: netwithgw1
        - name: MACVLAN_IP
          value: "10.0.0.1"
        - name: MACVLAN_SUBNET
          value: "24"
        - name: ROUTES
        - name: MANAGERS
      name: init-vlan
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  containers:
    - name: ubuntu
      image: ubuntu:latest
      env:
        - name: VLAN_IP
          value: "10.0.0.1"
        - name: VLAN_SUBNET
          value: "24"
status:
  containerStatuses:
    - name: ubuntu
      ready: true
      restartCount: 0
      started: true
---
apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: netwithgw1
spec:
  vlanId: 110
  gateways:
    - address: "10.0.1.1/24"
      routes:
        - dest: 10.10.10.10/24
          src: none
  pools:
    - name: primary
      description: primary pool
      addresses:
        - "10.0.0.1/24"
      routes:
        - dest: "10.0.1.1/32"
          src: self
          scopeLink: true
        - dest: "10.10.10.10"
          via: "10.0.1.1"
          src: none
status:
  freeIPs:
    primary: []
  pendingIPs:
    primary: {}
