apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: neteditable1
spec:
  vlanId: 110
  gateways:
    - address: "10.0.1.1/24"
      routes:
        - dest: "10.10.10.10/24"
          src: "none"
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - "10.0.0.1/24"
      routes:
        - dest: "10.0.1.1/32"
          src: "self"
          scopeLink: true
        - dest: "10.10.10.10"
          via: "10.0.1.1"
          src: none
