apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: neteditable2
spec:
  vlanId: 130
  localSubnet:
    - "192.168.30.0/24"
  remoteSubnet:
    - "192.168.40.0/24"
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - "192.168.30.10"
  localGatewayIp: "192.168.100.2"
  excludedNodes: []
