apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: neteditable2
spec:
  vlanId: 130
  localGatewayIp: "192.168.100.2"
  localSubnet:
    - "192.168.30.0/24"
  remoteSubnet:
    - "192.168.40.0/24"
  pools:
    primary:
      - "192.168.30.10"
  excludedNodes: []
