apiVersion: v1
kind: Pod
metadata:
  name: neteditable1-pod-1
  annotations:
    vlanman.dialo.ai/network: neteditable1
    vlanman.dialo.ai/pool: primary
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      readinessProbe:
        exec:
          command:
            - ping
            - -c
            - "1"
            - "10.10.10.10"
        initialDelaySeconds: 10
        periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: neteditable2-pod-1
  annotations:
    vlanman.dialo.ai/network: neteditable2
    vlanman.dialo.ai/pool: primary
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      readinessProbe:
        exec:
          command:
            - ping
            - -c
            - "1"
            - "10.10.10.10"
        initialDelaySeconds: 10
        periodSeconds: 5
