apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: neteditable2
spec:
  excludedNodes: []
  localGatewayIp: "192.168.100.2"
  localSubnet:
    - "192.168.30.0/24"
  remoteSubnet:
    - "192.168.40.0/24"
  vlanId: 130
status:
  freeIPs:
    primary: []
  pendingIPs: {}
---
apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: neteditable1
spec:
  excludedNodes: []
  localGatewayIp: "192.168.100.1"
  localSubnet:
    - "192.168.100.0/24"
  remoteSubnet:
    - "192.168.200.0/24"
  vlanId: 120
status:
  freeIPs:
    primary: []
  pendingIPs: {}
