# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: edit
spec:
  steps:
  - name: step-01
    try:
    - apply:
        file: 01-valid-network.yaml
    - assert:
        file: 01-assert.yaml
  - name: step-02
    try:
    - apply:
        file: 02-another-network.yaml
    - assert:
        file: 02-assert.yaml
  - name: step-03
    try:
    - apply:
        file: 03-add-pods.yaml
    - assert:
        file: 03-assert.yaml
  - name: step-04
    try:
    - delete:
        ref:
          apiVersion: v1
          kind: Pod
          name: neteditable1-pod-1
    - delete:
        ref:
          apiVersion: v1
          kind: Pod
          name: neteditable2-pod-1
