apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net2
spec:
  vlanId: 200
  localSubnet:
    - "192.168.200.0/24"
  remoteSubnet:
    - "192.168.30.0/24"
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - "192.168.200.10"
        - "192.168.200.11"
        - "192.168.200.12"
  excludedNodes: []
  localGatewayIp: "192.168.100.2"
status:
  freeIPs:
    primary:
      - 192.168.200.10
      - 192.168.200.11
      - 192.168.200.12
