apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net2
spec:
  vlanId: 200
  localGatewayIp: "192.168.100.2"
  localSubnet:
    - "192.168.200.0/24"
  remoteSubnet:
    - "192.168.30.0/24"
  pools:
    primary:
      - 192.168.200.10
      - 192.168.200.11
      - 192.168.200.12
  excludedNodes: []
status:
  freeIPs:
    primary:
      - 192.168.200.10
      - 192.168.200.11
      - 192.168.200.12
