apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net1
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-manager-net1
  namespace: vlanman-system
  labels:
    vlanman.dialo.ai/manager: net1
---
apiVersion: v1
kind: Service
metadata:
  name: net1-service
  namespace: vlanman-system
