apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net3
spec:
  excludedNodes: ["k3s-1"]
  localGatewayIp: "192.168.100.3"
  localSubnet:
    - "192.168.30.0/24"
  remoteSubnet:
    - "192.168.40.0/24"
  pools:
    primary:
      - "192.168.30.10"
      - "192.168.30.11"
      - "192.168.30.12"
  vlanId: 300
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-manager-net3
  namespace: vlanman-system
  labels:
    vlanman.dialo.ai/manager: net3
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k3s-1
      containers:
        - env:
            - name: VLAN_ID
              value: "300"
            - name: NAMESPACE
              value: vlanman-system
            - name: LOCK_NAME
              value: vlanman-leader-election-net3
            - name: OWNER_NETWORK
              value: net3
            - name: LOCAL_GATEWAY_IP
              value: 192.168.100.3
            - name: LOCAL_GATEWAY_SUBNET
              value: "32"
            - name: REMOTE_ROUTES
              value: 192.168.40.0/24
            - name: LOCAL_ROUTES
              value: 192.168.30.0/24
          image: 192.168.10.201:5000/vlan-manager:latest-dev
          name: vlan-manager
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostPID: true
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: create-vlan-job-net3-k3s-2
  name: create-vlan-job-net3-k3s-2
  namespace: vlanman-system
spec:
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: create-vlan-job-net3-k3s-2
        job-name: create-vlan-job-net3-k3s-2
    spec:
      containers:
        - env:
            - name: PID
            - name: ID
              value: "300"
          image: 192.168.10.201:5000/vlan-interface:latest-dev
          imagePullPolicy: Always
          name: create-vlan
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/hostname: k3s-2
status:
  ready: 0
  succeeded: 1
  terminating: 0
---
apiVersion: v1
kind: Service
metadata:
  name: net3-service
  namespace: vlanman-system
spec:
  internalTrafficPolicy: Local
  ports:
    - name: manager
      port: 61410
      protocol: TCP
      targetPort: 61410
  selector:
    vlanman.dialo.ai/manager: net3
