apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net3
spec:
  vlanId: 300
  localSubnet:
    - "192.168.30.0/24"
  remoteSubnet:
    - "192.168.40.0/24"
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - "192.168.30.10"
        - "192.168.30.11"
        - "192.168.30.12"
  localGatewayIp: "192.168.100.3"
  managerAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - k3s-1
