apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net3
spec:
  vlanId: 300
  localGatewayIp: "192.168.100.3"
  localSubnet:
    - "192.168.30.0/24"
  remoteSubnet:
    - "192.168.40.0/24"
  pools:
    primary:
      - "192.168.30.10"
      - "192.168.30.11"
      - "192.168.30.12"
  excludedNodes: ["k3s-1"]
