apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net4
spec:
  managerAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - k3s-2
  localSubnet:
    - "192.168.40.0/24"
  remoteSubnet:
    - "192.168.50.0/24"
  vlanId: 400
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - "192.168.40.10"
        - "192.168.40.11"
        - "192.168.40.12"
  localGatewayIp: "192.168.100.4"
status:
  freeIPs:
    primary:
      - "192.168.40.10"
      - "192.168.40.11"
      - "192.168.40.12"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-manager-net4
  namespace: vlanman-system
  labels:
    vlanman.dialo.ai/manager: net4
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k3s-2
      containers:
        - env:
            - name: VLAN_ID
              value: "400"
            - name: NAMESPACE
              value: vlanman-system
            - name: LOCK_NAME
              value: vlanman-leader-election-net4
            - name: OWNER_NETWORK
              value: net4
            - name: LOCAL_GATEWAY_IP
              value: 192.168.100.4
            - name: LOCAL_GATEWAY_SUBNET
              value: "32"
            - name: REMOTE_ROUTES
              value: 192.168.50.0/24
            - name: LOCAL_ROUTES
              value: 192.168.40.0/24
          image: 192.168.10.201:5000/vlan-manager:dev
          name: vlan-manager
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostPID: true
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: create-vlan-job-net4-k3s-1
  name: create-vlan-job-net4-k3s-1
  namespace: vlanman-system
spec:
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: create-vlan-job-net4-k3s-1
        job-name: create-vlan-job-net4-k3s-1
    spec:
      containers:
        - env:
            - name: PID
            - name: ID
              value: "400"
            - name: INTERFACE
          image: 192.168.10.201:5000/vlan-interface:dev
          imagePullPolicy: Always
          name: create-vlan
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/hostname: k3s-1
status:
  ready: 0
  succeeded: 1
  terminating: 0
---
apiVersion: v1
kind: Service
metadata:
  name: net4-service
  namespace: vlanman-system
spec:
  internalTrafficPolicy: Local
  ports:
    - name: manager
      port: 61410
      protocol: TCP
      targetPort: 61410
  selector:
    vlanman.dialo.ai/manager: net4
