# Verify net3 and net4 still exist (should not be deleted)
apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net3
spec:
  managerAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - k3s-1
  localSubnet:
    - 192.168.30.0/24
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - 192.168.30.10
        - 192.168.30.11
        - 192.168.30.12
  remoteSubnet:
    - 192.168.40.0/24
  vlanId: 300
  localGatewayIp: 192.168.100.3
status:
  freeIPs:
    primary:
      - 192.168.30.10
      - 192.168.30.11
      - 192.168.30.12
---
apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net4
spec:
  managerAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - k3s-2
  vlanId: 400
  localSubnet:
    - 192.168.40.0/24
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - 192.168.40.10
        - 192.168.40.11
        - 192.168.40.12
  remoteSubnet:
    - 192.168.50.0/24
  localGatewayIp: 192.168.100.4
status:
  freeIPs:
    primary:
      - 192.168.40.10
      - 192.168.40.11
      - 192.168.40.12
---
# Verify net3 and net4 DaemonSets still exist
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-manager-net3
  namespace: vlanman-system
  labels:
    vlanman.dialo.ai/manager: net3
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-manager-net4
  namespace: vlanman-system
  labels:
    vlanman.dialo.ai/manager: net4
---
# Verify net3 and net4 Jobs still exist
apiVersion: batch/v1
kind: Job
metadata:
  name: create-vlan-job-net3-k3s-2
  namespace: vlanman-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-vlan-job-net4-k3s-1
  namespace: vlanman-system
