apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net2
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-manager-net2
  namespace: vlanman-system
  labels:
    vlanman.dialo.ai/manager: net2
---
apiVersion: v1
kind: Service
metadata:
  name: net2-service
  namespace: vlanman-system
spec:
  internalTrafficPolicy: Local
  ports:
    - name: manager
      port: 61410
      protocol: TCP
      targetPort: 61410
  selector:
    vlanman.dialo.ai/manager: net2
