apiVersion: kuttl.dev/v1beta1
kind: TestStep
delete:
  - apiVersion: vlanman.dialo.ai/v1
    kind: VlanNetwork
    metadata:
      name: net3
    spec:
      managerAffinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k3s-1
      gatewayIp: "192.168.100.3"
      localSubnet: "192.168.30.0/24"
      remoteSubnet: "192.168.40.0/24"
      vlanId: 300
  - apiVersion: vlanman.dialo.ai/v1
    kind: VlanNetwork
    metadata:
      name: net4
    spec:
      managerAffinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k3s-2
      gatewayIp: "192.168.100.4"
      localSubnet: "192.168.40.0/24"
      remoteSubnet: "192.168.50.0/24"
      vlanId: 400
