apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net5
spec:
  localSubnet:
    - "192.168.50.0/24"
  remoteSubnet:
    - "192.168.60.0/24"
  vlanId: 500
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - "192.168.50.10"
        - "192.168.50.11"
        - "192.168.50.12"
  localGatewayIp: "192.168.100.5"
status:
  freeIPs:
    primary:
      - "192.168.50.10"
      - "192.168.50.11"
      - "192.168.50.12"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-manager-net5
  namespace: vlanman-system
  labels:
    vlanman.dialo.ai/manager: net5
spec:
  template:
    spec:
      containers:
        - env:
            - name: VLAN_ID
              value: "500"
            - name: NAMESPACE
              value: vlanman-system
            - name: LOCK_NAME
              value: vlanman-leader-election-net5
            - name: OWNER_NETWORK
              value: net5
            - name: LOCAL_GATEWAY_IP
              value: 192.168.100.5
            - name: LOCAL_GATEWAY_SUBNET
              value: "32"
            - name: REMOTE_ROUTES
              value: 192.168.60.0/24
            - name: LOCAL_ROUTES
              value: 192.168.50.0/24
          image: 192.168.10.201:5000/vlan-manager:latest-dev
          name: vlan-manager
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostPID: true
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 2
  numberMisscheduled: 0
  numberReady: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: create-vlan-job-net5-k3s-1
  name: create-vlan-job-net5-k3s-1
  namespace: vlanman-system
spec:
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: create-vlan-job-net5-k3s-1
        job-name: create-vlan-job-net5-k3s-1
    spec:
      containers:
        - env:
            - name: PID
            - name: ID
              value: "500"
            - name: INTERFACE
          image: 192.168.10.201:5000/vlan-interface:latest-dev
          imagePullPolicy: Always
          name: create-vlan
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/hostname: k3s-1
status:
  ready: 0
  succeeded: 1
  terminating: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: create-vlan-job-net5-k3s-2
  name: create-vlan-job-net5-k3s-2
  namespace: vlanman-system
spec:
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: create-vlan-job-net5-k3s-2
        job-name: create-vlan-job-net5-k3s-2
    spec:
      containers:
        - env:
            - name: PID
            - name: ID
              value: "500"
            - name: INTERFACE
          image: 192.168.10.201:5000/vlan-interface:latest-dev
          imagePullPolicy: Always
          name: create-vlan
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/hostname: k3s-2
status:
  ready: 0
  succeeded: 1
  terminating: 0
---
apiVersion: v1
kind: Service
metadata:
  name: net5-service
  namespace: vlanman-system
spec:
  internalTrafficPolicy: Local
  ports:
    - name: manager
      port: 61410
      protocol: TCP
      targetPort: 61410
  selector:
    vlanman.dialo.ai/manager: net5
