apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: net5
spec:
  vlanId: 500
  localSubnet:
    - "192.168.50.0/24"
  remoteSubnet:
    - "192.168.60.0/24"
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - "192.168.50.10"
        - "192.168.50.11"
        - "192.168.50.12"
  localGatewayIp: "192.168.100.5"
  excludedNodes: []
status:
  freeIPs:
    primary:
      - "192.168.50.10"
      - "192.168.50.11"
      - "192.168.50.12"
