apiVersion: kuttl.dev/v1beta1
kind: TestStep
delete:
  - apiVersion: vlanman.dialo.ai/v1
    kind: VlanNetwork
    metadata:
      name: net5
    spec:
      excludedNodes: []
      gatewayIp: "192.168.100.5"
      localSubnet: "192.168.50.0/24"
      remoteSubnet: "192.168.60.0/24"
      vlanId: 500
