apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: netwithpods1
spec:
  vlanId: 110
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - "10.0.0.1/32"
      routes:
        - dest: "10.10.10.10/32"
          src: "self"
          scopeLink: true
status:
  freeIPs:
    primary:
      - "10.0.0.1/32"
  pendingIPs:
    primary: {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-manager-netwithpods1
  namespace: vlanman-system
  labels:
    vlanman.dialo.ai/manager: netwithpods1
spec:
  template:
    spec:
      containers:
        - env:
            - name: VLAN_ID
              value: "110"
            - name: NAMESPACE
              value: vlanman-system
            - name: LOCK_NAME
              value: vlanman-leader-election-netwithpods1
            - name: OWNER_NETWORK
              value: netwithpods1
            # no need to check the exact values since there is a readyness probe now
            - name: POOLS
            - name: GATEWAYS
          image: 192.168.10.201:5000/vlan-manager:dev
          name: vlan-manager
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostPID: true
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 2
  numberMisscheduled: 0
  numberReady: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: create-vlan-job-netwithpods1-k3s-1
  name: create-vlan-job-netwithpods1-k3s-1
  namespace: vlanman-system
spec:
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: create-vlan-job-netwithpods1-k3s-1
        job-name: create-vlan-job-netwithpods1-k3s-1
    spec:
      containers:
        - env:
            - name: PID
            - name: ID
              value: "110"
            - name: INTERFACE
          image: 192.168.10.201:5000/vlan-interface:dev
          imagePullPolicy: Always
          name: create-vlan
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/hostname: k3s-1
status:
  ready: 0
  succeeded: 1
  terminating: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: create-vlan-job-netwithpods1-k3s-2
  name: create-vlan-job-netwithpods1-k3s-2
  namespace: vlanman-system
spec:
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: create-vlan-job-netwithpods1-k3s-2
        job-name: create-vlan-job-netwithpods1-k3s-2
    spec:
      containers:
        - env:
            - name: PID
            - name: ID
              value: "110"
            - name: INTERFACE
          image: 192.168.10.201:5000/vlan-interface:dev
          imagePullPolicy: Always
          name: create-vlan
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/hostname: k3s-2
status:
  ready: 0
  succeeded: 1
  terminating: 0
---
apiVersion: v1
kind: Service
metadata:
  name: netwithpods1-service
  namespace: vlanman-system
spec:
  internalTrafficPolicy: Local
  ports:
    - name: manager
      port: 61410
      protocol: TCP
      targetPort: 61410
  selector:
    vlanman.dialo.ai/manager: netwithpods1
