apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: netwithpods1
spec:
  vlanId: 110
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - "10.0.0.1/32"
      routes:
        - dest: "10.10.10.10/32"
          src: "self"
          scopeLink: true
