apiVersion: v1
kind: Pod
metadata:
  name: netwithpods1-pod-1
  annotations:
    vlanman.dialo.ai/network: netwithpods1
    vlanman.dialo.ai/pool: primary
  labels:
    vlanman.dialo.ai/worker: netwithpods1
spec:
  initContainers:
    - env:
        - name: VLAN_NETWORK
          value: netwithpods1
        - name: MACVLAN_IP
          value: "192.168.100.10"
        - name: MACVLAN_SUBNET
          value: "32"
        - name: REMOTE_ROUTES
          value: 192.168.200.0/24
        - name: GATEWAY_IP
        - name: GATEWAY_SUBNET
        - name: MANAGERS
      name: init-vlan
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      env:
        - name: VLAN_IP
          value: "192.168.100.10"
        - name: VLAN_SUBNET
          value: "32"
---
apiVersion: vlanman.dialo.ai/v1
kind: VlanNetwork
metadata:
  name: netwithpods1
spec:
  localGatewayIp: "192.168.100.1"
  localSubnet:
    - "192.168.100.0/24"
  pools:
    - name: primary
      description: "Primary IP pool"
      addresses:
        - 192.168.100.10
        - 192.168.100.11
        - 192.168.100.12
  remoteSubnet:
    - 192.168.200.0/24
  vlanId: 110
status:
  freeIPs:
    primary:
      - "192.168.100.11"
      - "192.168.100.12"
  pendingIPs:
    primary: {}
