# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: createpods
spec:
  steps:
    - name: step-01
      try:
        - apply:
            file: 01-valid-network.yaml
        - assert:
            file: 01-assert.yaml
    - name: step-02
      try:
        - apply:
            file: 02-add-single-pod.yaml
        - assert:
            file: 02-assert.yaml
    - name: step-03
      try:
        - delete:
            file: 03-delete.yaml
        - error:
            file: 03-errors.yaml
    - name: step-04
      try:
        - delete:
            file: 04-delete.yaml
        - error:
            file: 04-errors.yaml
