# Default values for vlanman
# This is a YAML-formatted file.
# Global configuration
global:
  namespace: "vlanman-system"
  monitoring:
    enabled: false
    interval: 5s
    release: kube-prometheus-stack
# Controller (operator) configuration
controller:
  podTimeoutSeconds: 60
  replicaCount: 1
  image: "plan9better/vlanman:0.1.0"
  pullPolicy: Always
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
manager:
  image: "plan9better/vlan-manager:0.1.0"
  pullPolicy: "Always"
worker:
  image: "plan9better/vlan-worker:0.1.0"
  pullPolicy: "Always"
interface:
  image: "plan9better/vlan-interface:0.1.0"
  pullPolicy: "Always"
  jobTTLSeconds: 300 # negative values mean never
# Webhook configuration
webhook:
  serviceName: "vlanman-webhook-service"
  mutatingWebhookName: "vlanman-mutating-webhook"
  validatingWebhookName: "vlanman-validating-webhook"
  certificate:
    name: "vlanman-webhook-certificate"
    secretName: "vlanman-webhook-cert-secret"
    issuerName: "selfsigned-issuer"
  volumes:
    name: "webhook-certs"
    mountPath: "/etc/webhook/certs"
    readOnly: true
# RBAC configuration
rbac:
  clusterRoleName: "vlanman-cluster-resource-access"
  clusterRoleBindingName: "vlanman-role-binding"
# Service account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "vlanman-service-account"
# Pod configuration
podAnnotations: {}
podLabels: {}
